version: "3.9"
services:

 node_test:
    build: .
    image: ui_erp:8.0-${BUILD_NUMBER}
    container_name: node_test
    environment:
        - TZ=Asia/Kolkata
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - "/etc/timezone:/etc/timezone:ro" 
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 3000:3000
    networks:
      - default

    restart: always
